In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# import the google stock data
stock_train = pd.read_csv(r"D:\Datasets\Deep Learning\Google_Stock_Price_Train.csv")

In [4]:
stock_train.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [5]:
len(stock_train)

1258

In [6]:
# Scaling ;  MinMax ;  between 0 and 1
from sklearn.preprocessing import MinMaxScaler

In [7]:
# numpy array
training_set = stock_train.iloc[:,1:2].values

In [8]:
type(training_set)

numpy.ndarray

In [9]:
training_set

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [10]:
sc = MinMaxScaler(feature_range=(0,1))

In [11]:
training_set_scaled = sc.fit_transform(training_set)

In [12]:
training_set_scaled

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [13]:
len(training_set)

1258

Creating a Data structure with 60 Timesteps and 1 Output
60 = 3 months

In [15]:
# create empty list
X_train=[]
y_train=[]
for i in range(60,1258):
    # 0 to 59 
    # 1 to 60
    X_train.append(training_set_scaled[i-60:i,0])  # 0 t0 59
    # 60th
    # 61th
    y_train.append(training_set_scaled[i,0]) 

In [16]:
print(len(X_train),"x")
print(len(y_train),"y")

1198 x
1198 y


In [17]:
# X_train[0]
print(X_train[0:1],"x")
print(y_train[0:1],"y")

[array([0.08581368, 0.09701243, 0.09433366, 0.09156187, 0.07984225,
       0.0643277 , 0.0585423 , 0.06568569, 0.06109085, 0.06639259,
       0.0614257 , 0.07474514, 0.02797827, 0.02379269, 0.02409033,
       0.0159238 , 0.01078949, 0.00967334, 0.01642607, 0.02100231,
       0.02280676, 0.02273235, 0.02810849, 0.03212665, 0.0433812 ,
       0.04475779, 0.04790163, 0.0440695 , 0.04648783, 0.04745517,
       0.04873875, 0.03936305, 0.04137213, 0.04034898, 0.04784582,
       0.04325099, 0.04356723, 0.04286033, 0.04602277, 0.05398467,
       0.05738894, 0.05714711, 0.05569611, 0.04421832, 0.04514845,
       0.04605997, 0.04412531, 0.03675869, 0.04486941, 0.05065481,
       0.05214302, 0.05612397, 0.05818885, 0.06540665, 0.06882953,
       0.07243843, 0.07993526, 0.07846566, 0.08034452, 0.08497656])] x
[0.08627874097775134] y


In [18]:
#Testing

X_train_t=[]
y_train_t=[]

for i in range(60,1258):
    # 0 to 59
    X_train_t.append(training_set[i-60:i,0])
    # 60th
    y_train_t.append(training_set[i,0]) #

In [19]:
print(len(X_train_t))
print(len(y_train_t))

1198
1198


In [20]:
X_train_t

[array([325.25, 331.27, 329.83, 328.34, 322.04, 313.7 , 310.59, 314.43,
        311.96, 314.81, 312.14, 319.3 , 294.16, 291.91, 292.07, 287.68,
        284.92, 284.32, 287.95, 290.41, 291.38, 291.34, 294.23, 296.39,
        302.44, 303.18, 304.87, 302.81, 304.11, 304.63, 305.32, 300.28,
        301.36, 300.81, 304.84, 302.37, 302.54, 302.16, 303.86, 308.14,
        309.97, 309.84, 309.06, 302.89, 303.39, 303.88, 302.84, 298.88,
        303.24, 306.35, 307.15, 309.29, 310.4 , 314.28, 316.12, 318.06,
        322.09, 321.3 , 322.31, 324.8 ]),
 array([331.27, 329.83, 328.34, 322.04, 313.7 , 310.59, 314.43, 311.96,
        314.81, 312.14, 319.3 , 294.16, 291.91, 292.07, 287.68, 284.92,
        284.32, 287.95, 290.41, 291.38, 291.34, 294.23, 296.39, 302.44,
        303.18, 304.87, 302.81, 304.11, 304.63, 305.32, 300.28, 301.36,
        300.81, 304.84, 302.37, 302.54, 302.16, 303.86, 308.14, 309.97,
        309.84, 309.06, 302.89, 303.39, 303.88, 302.84, 298.88, 303.24,
        306.35, 307.15

In [21]:
print(y_train_t[0])
print(y_train_t[1])

325.5
324.66


In [22]:
# type
type(X_train)

list

In [23]:
# Convert X_train, y_train  into numpy array
X_train,y_train = np.array(X_train),np.array(y_train)

In [24]:
print(type(X_train))

<class 'numpy.ndarray'>


In [25]:
X_train.shape

(1198, 60)

In [26]:
len(y_train)

1198

In [27]:
## y_train is in  1 d array
y_train.shape

(1198,)

In [28]:
## (number of times the loop repeated,number of values added per loop)

###(number of samples,no.of time stamp)

## current dimension is 2 d

X_train.shape


(1198, 60)

In [29]:
# Reshape
## the lstm model accepts only 3d array.so we are reshaping it into 3d


####(number of samples,number of time stamp,no.of features)

# (1198,60,1)

X_train = np.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))

In [30]:
X_train.shape

(1198, 60, 1)

In [31]:
X_train.ndim

3

In [32]:
# Model buiding

# imp algo
from keras.models import Sequential

In [33]:
from keras.layers import Dense
from keras.layers import LSTM  # main layer
from keras.layers import Dropout  #  to avoid overfitting

In [34]:
# Initialize the model
stock_model = Sequential()

In [35]:
# Add the layers

# first layer:  input + hidden (LSMT)

stock_model.add(LSTM(units=50,return_sequences=True,input_shape=(X_train.shape[1],1)))
stock_model.add(Dropout(0.2))

# second hidden (LSTM)
stock_model.add(LSTM(units=50,return_sequences=True))
stock_model.add(Dropout(0.2))

# third hidden (LSTM)
stock_model.add(LSTM(units=50,return_sequences=False))
stock_model.add(Dropout(0.2))

# last;  output layer

stock_model.add(Dense(units=1),)

C:\Users\ABDUL HAMEED\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [36]:
# Compile the Model
stock_model.compile(optimizer='adam',loss='mean_squared_error')

In [ ]:
# Train the model
stock_model.fit(X_train,y_train,epochs=1000,batch_size=32)

Epoch 1/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 8s 59ms/step - loss: 0.0815
Epoch 2/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - loss: 0.0058
Epoch 3/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 0.0046
Epoch 4/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - loss: 0.0050
Epoch 5/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046
Epoch 6/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 0.0038
Epoch 7/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - loss: 0.0049
Epoch 8/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - loss: 0.0037
Epoch 9/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - loss: 0.0041
Epoch 10/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 68ms/step - loss: 0.0044
Epoch 11/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - loss: 0.0038
Epoch 12/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - loss: 0.0033
Epoch 13/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - loss: 0.0033
Epoch 14/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 0.0043
Epoch 15/1000
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s

In [ ]:
# Part3

# Making the Prediction and Visualizing the results

# Getting the real stock of 2017

stock_test = pd.read_csv(r"D:\Datasets\Deep Learning\Google_Stock_Price_Test.csv")

In [ ]:
stock_test.head()

In [ ]:
len(stock_test)

In [ ]:
# 2017 jan open prices -- real
real_stock_price  = stock_test.iloc[:,1:2].values

In [ ]:
len(real_stock_price)

In [ ]:
## adding the train and the test  dataset in open cloumn

stock_total = pd.concat((stock_train['Open'],stock_test['Open']),axis=0)

In [ ]:
len(stock_total)

In [ ]:
stock_total.head()

In [ ]:
stock_total.tail(5)

In [ ]:
print(len(stock_total))

print(len(stock_test))


In [ ]:
# Extracting the last 60 days before the test set and the entire test set for prediction inputs

inputs = stock_total[len(stock_total) - len(stock_test) - 60:].values

In [ ]:
len(inputs)

In [ ]:
inputs.shape

In [ ]:
inputs = inputs.reshape(-1,1)

#reshape(-1, 1) if your data has a single feature or array. reshape(1, -1) if it contains a single sample.

In [ ]:
inputs.shape

In [ ]:
# scaling;  MinMax
inputs = sc.transform(inputs)

In [ ]:

X_test = []

for i in range(60,80):    #  60 days;  80 =  60+20
    X_test.append(inputs[i-60:i,0])


In [ ]:
len(X_test)

In [ ]:
X_test[1]

In [ ]:
type(X_test)

In [ ]:
# convert list into numpy array
X_test = np.array(X_test)

In [ ]:
X_test.shape

In [ ]:
# Reshape

X_test = np.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

In [ ]:
X_test.shape

In [ ]:
X_test.ndim

In [ ]:

# Prediction
predicted_stock_prices = stock_model.predict(X_test)

In [ ]:
predicted_stock_prices[1]

In [ ]:
# predicted_stock_prices

In [ ]:
# inverse ...

predicted_stock_prices = sc.inverse_transform(predicted_stock_prices)

In [ ]:
predicted_stock_prices[1]

In [ ]:
# predicted_stock_prices

In [ ]:
len(predicted_stock_prices)

In [ ]:
# real_stock_price

In [ ]:
# Visualization for comparision:   line

plt.plot(real_stock_price,color='blue',label='Real Stock Prices')

plt.plot(predicted_stock_prices,color='red',label='Predicted Stock Prices')

plt.title('stock prediction')
plt.legend()
plt.show()

In [ ]:
import math
from sklearn.metrics import mean_squared_error,r2_score
rmse = math.sqrt(mean_squared_error(real_stock_price, predicted_stock_prices))
r2score =(r2_score(real_stock_price, predicted_stock_prices))

In [ ]:
print(rmse,"rmse" , "|" , r2score)

In [ ]:
stock_model.summary()

In [ ]:
stock_model.metrics